# vim: set et ts=2 sw=2 :

version: '3'

services:
  db:
    image: 'mysql:5'
    volumes:
      - 'db_data:/var/lib/mysql'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: 'lainchan-root'
      MYSQL_DATABASE: 'lainchan'
      MYSQL_USER: 'lainchan'
      MYSQL_PASSWORD: 'lainchan'

  lainchan:
    build: '.'
    volumes:
      - '.:/app'
    depends_on:
      - 'db'
    ports:
      - '8080:8080'

volumes:
  db_data:
