# vim: set et ts=2 sw=2 :

version: '3'

services:
  db:
    image: 'mysql:5'
    volumes:
      - 'db_data:/var/lib/mysql'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: 'wirechan-root'
      MYSQL_DATABASE: 'wirechan'
      MYSQL_USER: 'wirechan'
      MYSQL_PASSWORD: 'wirechan'

  wirechan:
    build: '.'
    restart: 'always'
    volumes:
      - '.:/app'
    depends_on:
      - 'db'
    ports:
      - '51109:8080'

volumes:
  db_data:
